#**Iris Flower Classification**

**Oasis Infobyte Tasks**

#**Author:Rudranarayan Baral**

#**Load Iris DataSet**

In [23]:
#Import Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

#**Check Data**

In [4]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

#**Check Targe Values**

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#**Check Labels**

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

#**Check Features Names**

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

#**Dependent and Independent Variable**

In [34]:
X=iris.data
Y=iris.target
Z=iris.target_names

#**Split Data into train and test Part**

In [9]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30,random_state=4)

In [12]:
X_train

array([[4.3, 3. , 1.1, 0.1],
       [5.7, 4.4, 1.5, 0.4],
       [5.9, 3. , 4.2, 1.5],
       [6.1, 3. , 4.6, 1.4],
       [6.5, 3. , 5.5, 1.8],
       [5.2, 3.5, 1.5, 0.2],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 2.6, 6.9, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.9, 4.2, 1.3],
       [5. , 3.5, 1.6, 0.6],
       [5.6, 2.9, 3.6, 1.3],
       [6. , 2.2, 5. , 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.6, 3. , 4.1, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.8, 3. , 5.5, 2.1],
       [6.7, 3. , 5. , 1.7],
       [6.5, 3.2, 5.1, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 2.5, 4.5, 1.7],
       [6.9, 3.2, 5.7, 2.3],
       [5.4, 3.4, 1.5, 0.4],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.6, 1.4, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.5, 2.8, 4.6, 1.5],
       [5.9, 3. , 5.1, 1.8],
       [6.3, 2.5, 4.9, 1.5],
       [4.9, 3

#**Use KNN Clasifier**

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
knn=KNeighborsClassifier(n_neighbors = 3)

#**Train KNN classifier**

In [15]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

#**Evaluate Models**

In [16]:
Y_pred = knn.predict(X_test)
Y_pred

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0,
       2])

In [17]:
Y_test

array([2, 0, 2, 2, 2, 1, 1, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0,
       2])

#**Check Accuracy Score**

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.9777777777777777

The iris datasets has 150 observations and 5 attributes or columns  of Iris Flowers.
First Four Columns are - Sepal Length,Sepal Width,Petal Length, Petal Width,all are  in cm.

The last column is containing the Classes - ['satosa','versicolor','virginica']

As we are loading the datasets from sklearn , the data set is already pre-processed.
So, the classes are -[0,1,2] instead of ['satosa','versicolor','virginica'].

In [24]:
#Data Shape
print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)


In [25]:
#Building the models
model = Sequential()
model.add(Dense(100,input_shape=(4,),activation="relu"))
model.add(Dense(3,activation='softmax'))

In [26]:
#Compiling the Models
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [27]:
#Fit the models
model.fit(X_train,Y_train,epochs=20)

Epoch 1/20
4/4 [==============================] - 1s 6ms/step - loss: 1.6101 - accuracy: 0.3810
Epoch 2/20
4/4 [==============================] - 0s 4ms/step - loss: 1.3359 - accuracy: 0.3810
Epoch 3/20
4/4 [==============================] - 0s 4ms/step - loss: 1.1889 - accuracy: 0.3905
Epoch 4/20
4/4 [==============================] - 0s 4ms/step - loss: 1.0966 - accuracy: 0.3714
Epoch 5/20
4/4 [==============================] - 0s 4ms/step - loss: 1.0667 - accuracy: 0.3429
Epoch 6/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0431 - accuracy: 0.3429
Epoch 7/20
4/4 [==============================] - 0s 4ms/step - loss: 1.0074 - accuracy: 0.3429
Epoch 8/20
4/4 [==============================] - 0s 4ms/step - loss: 0.9639 - accuracy: 0.3429
Epoch 9/20
4/4 [==============================] - 0s 5ms/step - loss: 0.9200 - accuracy: 0.3524
Epoch 10/20
4/4 [==============================] - 0s 5ms/step - loss: 0.8811 - accuracy: 0.5905
Epoch 11/20
4/4 [======================

In [28]:
#Evaluating the model
model.evaluate(X_test,Y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.5597 - accuracy: 0.7778


[0.5597070455551147, 0.7777777910232544]

In [29]:
#Predict for the first 10 observations
pred = model.predict(X_test[:10])

1/1 [==============================] - 0s 122ms/step


In [31]:
p = np.argmax(pred,axis=1)
print(p)
print(Y_test[:10])

[2 0 2 2 2 2 2 0 0 2]
[2 0 2 2 2 1 1 0 0 2]


In [35]:
#Prediction Result
for i in p :
  print("Predicted_Class: {},  Name: {}".format(i,Z[i]))

Predicted_Class: 2,  Name: virginica
Predicted_Class: 0,  Name: setosa
Predicted_Class: 2,  Name: virginica
Predicted_Class: 2,  Name: virginica
Predicted_Class: 2,  Name: virginica
Predicted_Class: 2,  Name: virginica
Predicted_Class: 2,  Name: virginica
Predicted_Class: 0,  Name: setosa
Predicted_Class: 0,  Name: setosa
Predicted_Class: 2,  Name: virginica
